# Generated by Django 5.1.7 on 2025-05-12 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('destination', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_participants', models.PositiveIntegerField()),
                ('available_slots', models.PositiveIntegerField()),
                ('guide_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_type',
            field=models.CharField(choices=[('HOTEL', 'Hotel'), ('FLIGHT', 'Flight'), ('TOUR', 'Tour')], default='HOTEL', max_length=6),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('HOTEL', 'Hotel'), ('FLIGHT', 'Flight'), ('TOUR', 'Tour')], default='HOTEL', max_length=6),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.tour'),
        ),
    ]
